services:
  pg-db:
    env_file:
      - .env
    image: pgvector/pgvector:pg18
    restart: always
    command: ["postgres", "-c", "log_statement=all", "-c", "log_duration=on"]
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=zula
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DATABASE_USERNAME} -d zula
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
