#!/bin/bash
# First-boot init for Docker Postgres. Mirrors devenv.nix services.postgres.initialDatabases.*.initialSQL.
set -euo pipefail

PS_REPLICATION_PASSWORD="${PS_REPLICATION_PASSWORD:-powersync}"
PS_STORAGE_USERNAME="${PS_STORAGE_USERNAME:-powersync}"
PS_STORAGE_PASSWORD="${PS_STORAGE_PASSWORD:-powersync}"
APP_USER="${POSTGRES_USER:?POSTGRES_USER is required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE EXTENSION IF NOT EXISTS vector;

	CREATE ROLE powersync_role WITH REPLICATION BYPASSRLS LOGIN PASSWORD '${PS_REPLICATION_PASSWORD}';
	GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO powersync_role;
	GRANT USAGE ON SCHEMA public TO powersync_role;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO powersync_role;
	GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO powersync_role;
	ALTER DEFAULT PRIVILEGES FOR ROLE "${APP_USER}" IN SCHEMA public
	  GRANT SELECT ON TABLES TO powersync_role;
	ALTER DEFAULT PRIVILEGES FOR ROLE "${APP_USER}" IN SCHEMA public
	  GRANT SELECT ON SEQUENCES TO powersync_role;
	CREATE PUBLICATION powersync FOR ALL TABLES;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER ${PS_STORAGE_USERNAME} WITH PASSWORD '${PS_STORAGE_PASSWORD}';
	CREATE DATABASE zula_powersync OWNER ${PS_STORAGE_USERNAME};
	GRANT CONNECT ON DATABASE zula_powersync TO powersync_role;
EOSQL
